version: '3.0'

services:
  zookeeper:
    container_name: "local-zookeeper"
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    logging:
      driver: none
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - local_net

  kafka:
    container_name: "local-kafka"
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    logging:
      driver: none
    depends_on:
      - zookeeper
    networks:
      - local_net


networks:
  local_net:
    driver: bridge